// This file is auto-generated by @hey-api/openapi-ts

export type OrganizationProfileOutputDto = {
  id: string
  name: string
  description: string
  organizationType?: string | null
  address?: {
    street?: string | null
    country?: string | null
    city?: string | null
    state?: string | null
    postcode?: string | null
  } | null
  logoImageUrl: string
  logoImageId?: {
    [key: string]: unknown
  }
  verificationDocumentUrl?: {
    [key: string]: unknown
  }
  verificationDocumentId?: {
    [key: string]: unknown
  }
  verificationRequestRemarks?: {
    [key: string]: unknown
  }
  verificationRequestedAt?: {
    [key: string]: unknown
  }
}

export type UserOutput = {
  id: string
  email: string
  fullName: string
  isEmailVerified: boolean
  isVerifiedByAdmin: boolean
  isSuperAdmin: boolean
  role:
    | 'SUPER_ADMIN'
    | 'ADMIN'
    | 'CONTENT_ADMIN'
    | 'ORGANIZATION'
    | 'INDIVIDUAL'
  gender: {
    [key: string]: unknown
  }
  phoneCountryCode: {
    [key: string]: unknown
  }
  phoneNumber: {
    [key: string]: unknown
  }
  profilePhotoUrl: {
    [key: string]: unknown
  }
  profilePhotoId: {
    [key: string]: unknown
  }
  bio: {
    [key: string]: unknown
  }
  linkedin: {
    [key: string]: unknown
  }
  currentRole: {
    [key: string]: unknown
  }
  bannerImageId?: {
    [key: string]: unknown
  }
  bannerImageUrl?: {
    [key: string]: unknown
  }
  socials?: {
    [key: string]: unknown
  }
  createdAt: string
  updatedAt: string
  organization?: OrganizationProfileOutputDto | null
}

export type ResponseMetadata = {
  count?: {
    [key: string]: unknown
  }
  additionalInfo?: {
    [key: string]: unknown
  }
}

export type UserApiResponse = {
  data: UserOutput
  meta: ResponseMetadata
}

export type BaseApiErrorObject = {
  statusCode: number
  message: string
  localizedMessage?: string
  errorName: string
  details: {
    [key: string]: unknown
  }
  path: string
  requestId: string
  timestamp: string
}

export type BaseApiErrorResponse = {
  error: BaseApiErrorObject
}

export type UpdateUserInput = {
  name?: string
  password?: string
  isEmailVerified?: boolean
  isVerifiedByAdmin?: boolean
  /**
   * Profile photo URL
   */
  profilePhotoUrl?: string
  /**
   * Profile photo ID
   */
  profilePhotoId?: string
  /**
   * User bio
   */
  bio?: string
  linkedin?: string
  currentRole?: string
  /**
   * Phone number (omit or null to clear)
   */
  phoneNumber?: {
    [key: string]: unknown
  }
  role?:
    | 'SUPER_ADMIN'
    | 'ADMIN'
    | 'CONTENT_ADMIN'
    | 'ORGANIZATION'
    | 'INDIVIDUAL'
}

export type UpdateMyOrganizationInput = {
  name?: string
  description?: string
  organizationType?: string | null
  address?: {
    street?: string | null
    country?: string | null
    city?: string | null
    state?: string | null
    postcode?: string | null
  }
  /**
   * Organization logo URL (ImageKit or CDN)
   */
  logoImageUrl?: string
  /**
   * Organization logo file id
   */
  logoImageId?: string
  bannerImageUrl?: string
  bannerImageId?: string
  socials?: {
    [key: string]: unknown
  }
  /**
   * Verification document image URL for admins to review
   */
  verificationDocumentUrl?: string
  /**
   * Verification document file id
   */
  verificationDocumentId?: string
  /**
   * Message to admins with the verification request
   */
  verificationRequestRemarks?: string
}

export type UserArrayApiResponse = {
  data: Array<UserOutput>
  meta: ResponseMetadata
}

export type PromoteUserInput = {
  role:
    | 'SUPER_ADMIN'
    | 'ADMIN'
    | 'CONTENT_ADMIN'
    | 'ORGANIZATION'
    | 'INDIVIDUAL'
}

export type LoginInput = {
  email: string
  password: string
}

export type AuthTokenOutput = {
  accessToken: string
  refreshToken: string
}

export type AuthTokenApiResponse = {
  data: AuthTokenOutput
  meta: ResponseMetadata
}

export type RegisterInput = {
  name: string
  username: string
  password: string
  email: string
  role:
    | 'SUPER_ADMIN'
    | 'ADMIN'
    | 'CONTENT_ADMIN'
    | 'ORGANIZATION'
    | 'INDIVIDUAL'
  orgName?: string
  orgType?: string
  province?: string
  district?: string
}

export type RegisterOutput = {
  id: number
  name: string
  username: string
  roles: Array<string>
  email: string
  isAccountDisabled: boolean
  role:
    | 'SUPER_ADMIN'
    | 'ADMIN'
    | 'CONTENT_ADMIN'
    | 'ORGANIZATION'
    | 'INDIVIDUAL'
  createdAt: string
  updatedAt: string
}

export type RegisterApiResponse = {
  data: RegisterOutput
  meta: ResponseMetadata
}

export type ResendVerificationInput = {
  /**
   * Email address to resend verification to
   */
  email: string
}

export type BaseApiResponse = {
  meta: {
    [key: string]: unknown
  }
}

export type ChangePasswordInput = {
  /**
   * Current password
   */
  currentPassword: string
  /**
   * New password
   */
  newPassword: string
}

export type RefreshTokenInput = {
  refreshToken: string
}

export type AddressResponse = {
  /**
   * Street
   */
  street?: string
  /**
   * Street
   */
  country?: string
  /**
   * Street
   */
  city?: string
  /**
   * Street
   */
  state?: string
  /**
   * Street
   */
  postcode?: string
}

export type OrganizationResponseDto = {
  /**
   * Organization id
   */
  id: string
  /**
   * Organization name
   */
  name: string
  /**
   * Organization description
   */
  description: string
  /**
   * Contact email from the linked user account (User.organizationId), if any
   */
  email?: {
    [key: string]: unknown
  }
  /**
   * Phone country code from the linked user account
   */
  phoneCountryCode?: {
    [key: string]: unknown
  }
  /**
   * Phone number from the linked user account
   */
  phoneNumber?: {
    [key: string]: unknown
  }
  /**
   * Address
   */
  address?: AddressResponse
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Banner image URL from the linked user account
   */
  bannerImageUrl?: string
  /**
   * Banner image ID from the linked user account
   */
  bannerImageId?: string
  /**
   * Logo image URL from the linked user account (profilePhotoUrl)
   */
  logoImageUrl: string
  /**
   * Logo image ID from the linked user account (profilePhotoId)
   */
  logoImageId?: string
  /**
   * True when a platform admin has verified the linked organization account holder
   */
  isVerifiedByAdmin: boolean
  /**
   * Tags IDs
   */
  tags?: Array<string>
  /**
   * Gallery
   */
  organizationGallery?: Array<string>
}

export type OrganizationArrayApiResponse = {
  data: Array<OrganizationResponseDto>
  meta: ResponseMetadata
}

export type AddressInput = {
  /**
   * Street
   */
  street?: string
  /**
   * Country
   */
  country?: string
  /**
   * City
   */
  city?: string
  /**
   * State
   */
  state?: string
  /**
   * Postcode
   */
  postcode?: string
}

export type CreateOrganizationDto = {
  /**
   * Organization name
   */
  name: string
  /**
   * Organization description
   */
  description: string
  /**
   * Address
   */
  address?: AddressInput
  /**
   * Gallery iamges
   */
  gallery?: Array<string>
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Logo image URL
   */
  logoImageUrl: string
  /**
   * Logo image ID
   */
  logoImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type OrganizationApiResponse = {
  data: OrganizationResponseDto
  meta: ResponseMetadata
}

export type UpdateOrganizationDto = {
  /**
   * Organization name
   */
  name: string
  /**
   * Organization description
   */
  description: string
  /**
   * Address
   */
  address?: AddressInput
  /**
   * Gallery iamges
   */
  gallery?: Array<string>
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Logo image URL
   */
  logoImageUrl: string
  /**
   * Logo image ID
   */
  logoImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type TagOutputDto = {
  [key: string]: unknown
}

export type TagArrayApiResponse = {
  data: Array<TagOutputDto>
  meta: ResponseMetadata
}

export type AddTagDto = {
  /**
   * The name of the tag
   */
  tag: string
  /**
   * Indicates if this is a user tag
   */
  isUserTag?: boolean
  /**
   * Indicates if this is an organization tag
   */
  isOrganizationTag?: boolean
  /**
   * Indicates if this is an event tag
   */
  isEventTag?: boolean
  /**
   * Indicates if this is a news tag
   */
  isNewsTag?: boolean
  /**
   * Indicates if this is a blog tag
   */
  isBlogTag?: boolean
  /**
   * Indicates if this is an opportunity tag
   */
  isOpportunityTag?: boolean
  /**
   * Indicates if this is a project tag
   */
  isProjectTag?: boolean
  /**
   * Indicates if this is a resource tag
   */
  isResourceTag?: boolean
}

export type TagApiResponse = {
  data: TagOutputDto
  meta: ResponseMetadata
}

export type ImagekitAuthParams = {
  /**
   * Imagekit token
   */
  token: string
  /**
   * Imagekit token expiry
   */
  expire: number
  /**
   * Imagekit auth sinature
   */
  signature: string
}

export type ImagekitResponseDto = {
  /**
   * Imagekit auth
   */
  ikAuthParams: ImagekitAuthParams
  /**
   * Imagekit pub key
   */
  publicKey: string
  /**
   * Imagekit endpoint
   */
  endpoint: string
  /**
   * Upload folder
   */
  folder: string
}

export type ImagekitApiResponse = {
  data: ImagekitResponseDto
  meta: ResponseMetadata
}

export type EventResponseDto = {
  /**
   * Event id
   */
  id: string
  /**
   * Event name
   */
  title: string
  /**
   * organizer
   */
  organizer: string
  /**
   * Event description
   */
  description: string
  /**
   * location
   */
  location: string
  /**
   * location type
   */
  locationType: string
  /**
   * event type
   */
  type: string
  /**
   * event type
   */
  format: string
  /**
   * event website
   */
  website: string
  /**
   * Contributed by
   */
  contributedBy: string
  /**
   * date
   */
  startDate?: string
  /**
   * date
   */
  registrationDeadline?: string
  /**
   * link
   */
  registrationLink?: string
  /**
   * email contact
   */
  contactEmail?: string
  /**
   * status
   */
  status?:
    | 'DRAFT'
    | 'UNDER_REVIEW'
    | 'PUBLISHED'
    | 'REJECTED'
    | 'IMPROVEMENT_REQUIRED'
  /**
   * cost
   */
  cost?: string
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Address
   */
  address?: AddressResponse
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Tags IDs
   */
  tags?: Array<string>
  /**
   * Gallery
   */
  eventGallery?: Array<string>
  /**
   * Draft status
   */
  isDraft: boolean
}

export type EventArrayApiResponse = {
  data: Array<EventResponseDto>
  meta: ResponseMetadata
}

export type CreateEventDto = {
  /**
   * Event name
   */
  title: string
  /**
   * organizer
   */
  organizer: string
  /**
   * Event description
   */
  description: string
  /**
   * location
   */
  location: string
  /**
   * location type
   */
  locationType: string
  /**
   * event type
   */
  type: string
  /**
   * event type
   */
  format: string
  /**
   * date
   */
  startDate?: string
  /**
   * date
   */
  registrationDeadline?: string
  /**
   * link
   */
  registrationLink?: string
  /**
   * email contact
   */
  contactEmail?: string
  /**
   * status
   */
  status?:
    | 'DRAFT'
    | 'UNDER_REVIEW'
    | 'PUBLISHED'
    | 'REJECTED'
    | 'IMPROVEMENT_REQUIRED'
  /**
   * cost
   */
  cost?: string
  /**
   * Address
   */
  address?: AddressInput
  /**
   * Gallery iamges
   */
  gallery?: Array<string>
  /**
   * website
   */
  website?: string
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type EventApiResponse = {
  data: EventResponseDto
  meta: ResponseMetadata
}

export type UpdateEventDto = {
  /**
   * Event name
   */
  title: string
  /**
   * organizer
   */
  organizer: string
  /**
   * Event description
   */
  description: string
  /**
   * location
   */
  location: string
  /**
   * location type
   */
  locationType: string
  /**
   * event type
   */
  type: string
  /**
   * event type
   */
  format: string
  /**
   * website
   */
  website?: string
  /**
   * date
   */
  startDate?: string
  /**
   * date
   */
  registrationDeadline?: string
  /**
   * link
   */
  registrationLink?: string
  /**
   * email contact
   */
  contactEmail?: string
  /**
   * status
   */
  status?:
    | 'DRAFT'
    | 'UNDER_REVIEW'
    | 'PUBLISHED'
    | 'REJECTED'
    | 'IMPROVEMENT_REQUIRED'
  /**
   * cost
   */
  cost?: string
  /**
   * Address
   */
  address?: AddressInput
  /**
   * Gallery iamges
   */
  gallery?: Array<string>
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
  /**
   * Event status
   */
  isDraft: boolean
}

export type ContentModerationDto = {
  action: 'APPROVE' | 'REQUEST_IMPROVEMENTS' | 'REJECT'
  feedback?: string
}

export type ApiResponseOfNewsResponseDtoArray = {
  meta: {
    [key: string]: unknown
  }
  data: Array<NewsResponseDto>
}

export type CreateNewsDto = {
  /**
   * News title
   */
  title: string
  /**
   * News source
   */
  source: string
  /**
   * News mode
   */
  mode: string
  /**
   * Published date
   */
  publishedDate: string
  /**
   * News link
   */
  newsLink: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type NewsResponseDto = {
  /**
   * News ID
   */
  id: string
  /**
   * News title
   */
  title: string
  /**
   * News source
   */
  source: string
  /**
   * News mode
   */
  mode: string
  /**
   * Published date
   */
  publishedDate: string
  /**
   * Published year
   */
  publishedYear: string
  /**
   * News link
   */
  newsLink: string
  /**
   * Tags IDs
   */
  tags?: Array<string>
  /**
   * Contributed by
   */
  contributedBy: string
  /**
   * Created at
   */
  createdAt: string
  /**
   * Updated at
   */
  updatedAt: string
  /**
   * Deleted at
   */
  deletedAt?: string
  /**
   * isDraft
   */
  isDraft: boolean
}

export type ApiResponseOfNewsResponseDto = {
  meta: {
    [key: string]: unknown
  }
  data: NewsResponseDto
}

export type UpdateNewsDto = {
  /**
   * News title
   */
  title: string
  /**
   * News source
   */
  source: string
  /**
   * News mode
   */
  mode: string
  /**
   * Published date
   */
  publishedDate?: string
  /**
   * Published year
   */
  publishedYear?: string
  /**
   * News link
   */
  newsLink: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
  /**
   * isDraft
   */
  isDraft: boolean
}

export type OpportunityResponseDto = {
  /**
   * Opportunity ID
   */
  id: string
  /**
   * Opportunity name
   */
  title: string
  /**
   * organizer
   */
  organizer: string
  /**
   * Opportunity description
   */
  description: string
  /**
   * location
   */
  location: string
  /**
   * location type
   */
  locationType: string
  /**
   * Opportunity type
   */
  type: string
  /**
   * Opportunity type
   */
  format: string
  /**
   * duration
   */
  duration?: string
  /**
   * date
   */
  applicationDeadline?: string
  /**
   * email contact
   */
  contactEmail?: string
  /**
   * status
   */
  status?:
    | 'DRAFT'
    | 'UNDER_REVIEW'
    | 'PUBLISHED'
    | 'REJECTED'
    | 'IMPROVEMENT_REQUIRED'
  /**
   * cost
   */
  cost?: string
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Address
   */
  address?: AddressResponse
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Tags IDs
   */
  tags?: Array<string>
  /**
   * Gallery
   */
  OpportunityGallery?: Array<string>
  /**
   * isDraft
   */
  isDraft?: boolean
  /**
   * Website URL
   */
  websiteUrl: string
}

export type OpportunityArrayApiResponse = {
  data: Array<OpportunityResponseDto>
  meta: ResponseMetadata
}

export type CreateOpportunityDto = {
  /**
   * Opportunity name
   */
  title: string
  /**
   * Opportunity description
   */
  description: string
  /**
   * location
   */
  location: string
  /**
   * location type
   */
  locationType: string
  /**
   * Opportunity type
   */
  type: string
  /**
   * opportunity format
   */
  format: string
  /**
   * Website URL
   */
  websiteUrl: string
  /**
   * date
   */
  applicationDeadline?: string
  /**
   * duration
   */
  duration?: string
  /**
   * email contact
   */
  contactEmail?: string
  /**
   * status
   */
  status?:
    | 'DRAFT'
    | 'UNDER_REVIEW'
    | 'PUBLISHED'
    | 'REJECTED'
    | 'IMPROVEMENT_REQUIRED'
  /**
   * cost
   */
  cost?: string
  /**
   * organizer
   */
  organizer: string
  /**
   * Address
   */
  address?: AddressInput
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type OpportunityApiResponse = {
  data: OpportunityResponseDto
  meta: ResponseMetadata
}

export type UpdateOpportunityDto = {
  /**
   * Opportunity name
   */
  title: string
  /**
   * organizer
   */
  organizer: string
  /**
   * Opportunity description
   */
  description: string
  /**
   * location
   */
  location: string
  /**
   * location type
   */
  locationType: string
  /**
   * Opportunity type
   */
  type: string
  /**
   * Opportunity type
   */
  format: string
  /**
   * date
   */
  applicationDeadline?: string
  /**
   * email contact
   */
  contactEmail?: string
  /**
   * status
   */
  status?:
    | 'DRAFT'
    | 'UNDER_REVIEW'
    | 'PUBLISHED'
    | 'REJECTED'
    | 'IMPROVEMENT_REQUIRED'
  /**
   * cost
   */
  cost?: string
  /**
   * Address
   */
  address?: AddressInput
  /**
   * Object of Socials
   */
  socials?: {
    [key: string]: unknown
  }
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
  /**
   * isDraft
   */
  isDraft?: boolean
}

export type AdminAnalyticsOutput = {
  newsCount: number
  userCount: string
  eventCount: string
  opportunityCount: string
  blogCount: string
  adminCount: number
  organizationCount: number
  individualCount: number
  /** Organizations with a submitted verification request, awaiting admin review */
  pendingOrganizationVerificationCount: number
}

export type ApiResponseOfAdminAnalyticsOutput = {
  meta: {
    [key: string]: unknown
  }
  data: AdminAnalyticsOutput
}

export type MonthlyUserStatsDto = {
  month: string
  count: number
}

export type MonthlyUserStatsResponseDto = {
  monthlyStats: Array<MonthlyUserStatsDto>
  year: number
}

export type ApiResponseOfMonthlyUserStatsResponseDto = {
  meta: {
    [key: string]: unknown
  }
  data: MonthlyUserStatsResponseDto
}

export type CreateBlogDto = {
  /**
   * Blog title
   */
  title: string
  /**
   * Blog content
   */
  content: string
  /**
   * Blog excerpt
   */
  excerpt?: string
  /**
   * Blog author
   */
  author: string
  /**
   * Blog category
   */
  category: string
  /**
   * Category ID
   */
  categoryId?: string
  /**
   * Estimated reading time
   */
  readingTime?: string
  /**
   * Published date
   */
  publishedDate?: string
  /**
   * Is draft
   */
  isDraft?: boolean
  /**
   * Is featured
   */
  isFeatured?: boolean
  /**
   * Is top read
   */
  isTopRead?: boolean
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type AuthorOutputDto = {
  /**
   * Author ID
   */
  id: string
  /**
   * Author LinkedIn profile URL
   */
  linkedin?: string
  /**
   * Author current role
   */
  currentRole?: string
  /**
   * Author full name
   */
  fullName: string
  /**
   * Author email
   */
  email: string
  /**
   * Author bio
   */
  bio?: string
  /**
   * Author profile photo URL
   */
  profilePhotoUrl?: string
}

export type CategoryResponseDto = {
  id: string
  name: string
  description?: string
  type:
    | 'BLOG'
    | 'NEWS'
    | 'EVENTS'
    | 'OPPORTUNITY'
    | 'PROJECT'
    | 'RESOURCE'
    | 'ORGANIZATION'
  createdAt: string
  updatedAt: string
}

export type BlogResponseDto = {
  /**
   * Blog ID
   */
  id: string
  /**
   * Blog title
   */
  title: string
  /**
   * Blog content
   */
  content: string
  /**
   * Blog excerpt
   */
  excerpt?: string
  /**
   * Blog author
   */
  author: string
  /**
   * Blog category
   */
  category: string
  /**
   * Estimated reading time
   */
  readingTime?: string
  /**
   * Published date
   */
  publishedDate?: string
  /**
   * Is draft
   */
  isDraft: boolean
  /**
   * Is featured
   */
  isFeatured: boolean
  /**
   * Is top read
   */
  isTopRead: boolean
  /**
   * Approved by admin
   */
  approvedByAdmin: boolean
  /**
   * Blog status
   */
  status: 'DRAFT' | 'UNDER_REVIEW' | 'PUBLISHED' | 'REJECTED'
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Tags
   */
  tags?: Array<TagOutputDto>
  /**
   * Author details
   */
  authorUser?: AuthorOutputDto
  /**
   * Created at
   */
  createdAt: string
  /**
   * Updated at
   */
  updatedAt: string
  /**
   * Deleted at
   */
  deletedAt?: string
  /**
   * Category ID
   */
  categoryId?: string
  /**
   * Category data
   */
  categoryData?: CategoryResponseDto
}

export type BlogApiResponse = {
  data: BlogResponseDto
  meta: ResponseMetadata
}

export type BlogArrayApiResponse = {
  data: Array<BlogResponseDto>
  meta: ResponseMetadata
}

export type UpdateBlogDto = {
  /**
   * Blog title
   */
  title?: string
  /**
   * Blog content
   */
  content?: string
  /**
   * Blog excerpt
   */
  excerpt?: string
  /**
   * Blog author
   */
  author?: string
  /**
   * Blog category
   */
  category?: string
  /**
   * Category ID
   */
  categoryId?: string
  /**
   * Estimated reading time
   */
  readingTime?: string
  /**
   * Published date
   */
  publishedDate?: string
  /**
   * Is draft
   */
  isDraft?: boolean
  /**
   * Is featured
   */
  isFeatured?: boolean
  /**
   * Is top read
   */
  isTopRead?: boolean
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type CreateProjectDto = {
  title: string
  duration?: string
  overview: string
  description: string
  status?: 'ONGOING' | 'COMPLETED' | 'UPCOMING'
  bannerImageUrl?: string
  bannerImageId?: string
  isDraft?: boolean
  tagIds?: Array<string>
}

export type ProjectResponseDto = {
  id: string
  title: string
  duration?: string
  overview: string
  description: string
  status: 'ONGOING' | 'COMPLETED' | 'UPCOMING'
  bannerImageUrl?: string
  bannerImageId?: string
  isDraft: boolean
  tags?: Array<string>
  createdAt: string
  updatedAt: string
}

export type ApiResponseOfProjectResponseDto = {
  meta: {
    [key: string]: unknown
  }
  data: ProjectResponseDto
}

export type ApiResponseOfProjectResponseDtoArray = {
  meta: {
    [key: string]: unknown
  }
  data: Array<ProjectResponseDto>
}

export type UpdateProjectDto = {
  title: string
  duration?: string
  overview: string
  description: string
  status?: 'ONGOING' | 'COMPLETED' | 'UPCOMING'
  bannerImageUrl?: string
  bannerImageId?: string
  isDraft?: boolean
  tagIds?: Array<string>
}

export type CreateResourceDto = {
  /**
   * Resource title
   */
  title: string
  /**
   * Resource overview/description
   */
  overview?: string
  /**
   * Resource type
   */
  type:
    | 'DOCUMENTARY'
    | 'PODCASTS_AND_TELEVISION'
    | 'COURSES'
    | 'PLANS_AND_POLICIES'
    | 'DATA_RESOURCES'
    | 'PLATFORMS'
    | 'RESEARCH_ARTICLES'
    | 'THESES_AND_DISSERTATIONS'
    | 'CASE_STUDIES'
    | 'REPORTS'
    | 'TOOLKITS_AND_GUIDES'
  /**
   * Resource level
   */
  level?: 'INTERNATIONAL' | 'REGIONAL' | 'NATIONAL' | 'PROVINCIAL' | 'LOCAL'
  /**
   * Link/Source/Website
   */
  link?: string
  /**
   * Course provider
   */
  courseProvider?: string
  /**
   * Course platform
   */
  platform?: string
  /**
   * Course duration
   */
  duration?: string
  /**
   * Author
   */
  author?: string
  /**
   * Publication Year
   */
  publicationYear?: string
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Is draft
   */
  isDraft?: boolean
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type ResourceResponseDto = {
  id: string
  title: string
  overview?: string
  type:
    | 'DOCUMENTARY'
    | 'PODCASTS_AND_TELEVISION'
    | 'COURSES'
    | 'PLANS_AND_POLICIES'
    | 'DATA_RESOURCES'
    | 'PLATFORMS'
    | 'RESEARCH_ARTICLES'
    | 'THESES_AND_DISSERTATIONS'
    | 'CASE_STUDIES'
    | 'REPORTS'
    | 'TOOLKITS_AND_GUIDES'
  level?: 'INTERNATIONAL' | 'REGIONAL' | 'NATIONAL' | 'PROVINCIAL' | 'LOCAL'
  link?: string
  courseProvider?: string
  platform?: string
  duration?: string
  author?: string
  publicationYear?: string
  bannerImageUrl?: string
  bannerImageId?: string
  isDraft: boolean
  /**
   * Tags
   */
  tags?: Array<TagOutputDto>
  createdAt: string
  updatedAt: string
}

export type ApiResponseOfResourceResponseDto = {
  meta: {
    [key: string]: unknown
  }
  data: ResourceResponseDto
}

export type ApiResponseOfResourceResponseDtoArray = {
  meta: {
    [key: string]: unknown
  }
  data: Array<ResourceResponseDto>
}

export type UpdateResourceDto = {
  /**
   * Resource title
   */
  title: string
  /**
   * Resource overview/description
   */
  overview?: string
  /**
   * Resource type
   */
  type:
    | 'DOCUMENTARY'
    | 'PODCASTS_AND_TELEVISION'
    | 'COURSES'
    | 'PLANS_AND_POLICIES'
    | 'DATA_RESOURCES'
    | 'PLATFORMS'
    | 'RESEARCH_ARTICLES'
    | 'THESES_AND_DISSERTATIONS'
    | 'CASE_STUDIES'
    | 'REPORTS'
    | 'TOOLKITS_AND_GUIDES'
  /**
   * Resource level
   */
  level?: 'INTERNATIONAL' | 'REGIONAL' | 'NATIONAL' | 'PROVINCIAL' | 'LOCAL'
  /**
   * Link/Source/Website
   */
  link?: string
  /**
   * Course provider
   */
  courseProvider?: string
  /**
   * Course platform
   */
  platform?: string
  /**
   * Course duration
   */
  duration?: string
  /**
   * Author
   */
  author?: string
  /**
   * Publication Year
   */
  publicationYear?: string
  /**
   * Banner image URL
   */
  bannerImageUrl?: string
  /**
   * Banner image ID
   */
  bannerImageId?: string
  /**
   * Is draft
   */
  isDraft?: boolean
  /**
   * Tags IDs
   */
  tagIds?: Array<string>
}

export type CreateCategoryDto = {
  name: string
  description?: string
  type:
    | 'BLOG'
    | 'NEWS'
    | 'EVENTS'
    | 'OPPORTUNITY'
    | 'PROJECT'
    | 'RESOURCE'
    | 'ORGANIZATION'
}

export type UpdateCategoryDto = {
  name?: string
  description?: string
  type?:
    | 'BLOG'
    | 'NEWS'
    | 'EVENTS'
    | 'OPPORTUNITY'
    | 'PROJECT'
    | 'RESOURCE'
    | 'ORGANIZATION'
}

export type CreateChatSessionDto = {
  title?: string
}

export type AddMessageDto = {
  role: 'user' | 'assistant'
  content: string
}

export type UpdateSessionTitleDto = {
  title: string
}

export type CreateDocumentDto = {
  title: string
  sourceUrl?: string
  totalPages?: number
  mediaType?: string
}

export type CreateChunkDto = {
  documentId: string
  chunkIndex: number
  text: string
  /**
   * Embedding vector
   */
  vector: Array<string>
  pageStart?: number
  pageEnd?: number
  meta?: {
    [key: string]: unknown
  }
  collection?: string
  embedModel?: string
}

export type GetChunksDto = {
  /**
   * Array of chunk UUIDs to fetch
   */
  chunkIds: Array<string>
}

export type ChatRequestDto = {
  /**
   * User query about climate
   */
  query: string
  /**
   * Conversation history
   */
  conversation_history?: Array<string>
  /**
   * Existing conversation/session ID
   */
  conversation_id?: string
  /**
   * Number of documents to retrieve
   */
  top_k?: number
}

export type AppControllerGetHelloData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1'
}

export type AppControllerGetHelloResponses = {
  200: unknown
}

export type UserControllerGetMyProfileData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UserControllerGetMyProfileErrors = {
  401: BaseApiErrorResponse
}

export type UserControllerGetMyProfileError =
  UserControllerGetMyProfileErrors[keyof UserControllerGetMyProfileErrors]

export type UserControllerGetMyProfileResponses = {
  200: UserApiResponse
}

export type UserControllerGetMyProfileResponse =
  UserControllerGetMyProfileResponses[keyof UserControllerGetMyProfileResponses]

export type UserControllerUpdateMyProfileData = {
  body: UpdateUserInput
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UserControllerUpdateMyProfileErrors = {
  401: BaseApiErrorResponse
}

export type UserControllerUpdateMyProfileError =
  UserControllerUpdateMyProfileErrors[keyof UserControllerUpdateMyProfileErrors]

export type UserControllerUpdateMyProfileResponses = {
  200: UserApiResponse
}

export type UserControllerUpdateMyProfileResponse =
  UserControllerUpdateMyProfileResponses[keyof UserControllerUpdateMyProfileResponses]

export type UserControllerUpdateMyOrganizationData = {
  body: UpdateMyOrganizationInput
  path?: never
  query?: never
  url: '/api/v1/users/me/organization'
}

export type UserControllerUpdateMyOrganizationErrors = {
  401: BaseApiErrorResponse
}

export type UserControllerUpdateMyOrganizationError =
  UserControllerUpdateMyOrganizationErrors[keyof UserControllerUpdateMyOrganizationErrors]

export type UserControllerUpdateMyOrganizationResponses = {
  200: UserApiResponse
}

export type UserControllerUpdateMyOrganizationResponse =
  UserControllerUpdateMyOrganizationResponses[keyof UserControllerUpdateMyOrganizationResponses]

export type UserControllerGetUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
  }
  url: '/api/v1/users'
}

export type UserControllerGetUsersErrors = {
  401: BaseApiErrorResponse
}

export type UserControllerGetUsersError =
  UserControllerGetUsersErrors[keyof UserControllerGetUsersErrors]

export type UserControllerGetUsersResponses = {
  200: UserArrayApiResponse
}

export type UserControllerGetUsersResponse =
  UserControllerGetUsersResponses[keyof UserControllerGetUsersResponses]

export type UserControllerGetUserData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/api/v1/users/{id}'
}

export type UserControllerGetUserErrors = {
  404: BaseApiErrorResponse
}

export type UserControllerGetUserError =
  UserControllerGetUserErrors[keyof UserControllerGetUserErrors]

export type UserControllerGetUserResponses = {
  200: UserApiResponse
}

export type UserControllerGetUserResponse =
  UserControllerGetUserResponses[keyof UserControllerGetUserResponses]

export type UserControllerUpdateUserData = {
  body: UpdateUserInput
  path?: never
  query?: never
  url: '/api/v1/users/{id}'
}

export type UserControllerUpdateUserErrors = {
  404: BaseApiErrorResponse
}

export type UserControllerUpdateUserError =
  UserControllerUpdateUserErrors[keyof UserControllerUpdateUserErrors]

export type UserControllerUpdateUserResponses = {
  200: UserApiResponse
}

export type UserControllerUpdateUserResponse =
  UserControllerUpdateUserResponses[keyof UserControllerUpdateUserResponses]

export type UserControllerPromoteUserData = {
  body: PromoteUserInput
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/users/{id}/promote'
}

export type UserControllerPromoteUserResponses = {
  200: UserApiResponse
}

export type UserControllerPromoteUserResponse =
  UserControllerPromoteUserResponses[keyof UserControllerPromoteUserResponses]

export type AuthControllerLoginData = {
  body: LoginInput
  path?: never
  query?: never
  url: '/api/v1/auth/login'
}

export type AuthControllerLoginErrors = {
  401: BaseApiErrorResponse
}

export type AuthControllerLoginError =
  AuthControllerLoginErrors[keyof AuthControllerLoginErrors]

export type AuthControllerLoginResponses = {
  200: AuthTokenApiResponse
}

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses]

export type AuthControllerRegisterLocalData = {
  body: RegisterInput
  path?: never
  query?: never
  url: '/api/v1/auth/register'
}

export type AuthControllerRegisterLocalResponses = {
  201: RegisterApiResponse
}

export type AuthControllerRegisterLocalResponse =
  AuthControllerRegisterLocalResponses[keyof AuthControllerRegisterLocalResponses]

export type AuthControllerResendVerificationData = {
  body: ResendVerificationInput
  path?: never
  query?: never
  url: '/api/v1/auth/resend-verification'
}

export type AuthControllerResendVerificationErrors = {
  /**
   * Invalid email or user already verified
   */
  400: BaseApiErrorResponse
  /**
   * User not found
   */
  404: BaseApiErrorResponse
}

export type AuthControllerResendVerificationError =
  AuthControllerResendVerificationErrors[keyof AuthControllerResendVerificationErrors]

export type AuthControllerResendVerificationResponses = {
  /**
   * Verification email sent successfully
   */
  200: unknown
}

export type AuthControllerVerifyEmailData = {
  body?: never
  path?: never
  query: {
    token: string
  }
  url: '/api/v1/auth/verify-email'
}

export type AuthControllerVerifyEmailErrors = {
  /**
   * Invalid or expired token
   */
  400: BaseApiErrorResponse
  /**
   * User not found
   */
  404: BaseApiErrorResponse
}

export type AuthControllerVerifyEmailError =
  AuthControllerVerifyEmailErrors[keyof AuthControllerVerifyEmailErrors]

export type AuthControllerVerifyEmailResponses = {
  /**
   * Email verified successfully
   */
  200: BaseApiResponse
}

export type AuthControllerVerifyEmailResponse =
  AuthControllerVerifyEmailResponses[keyof AuthControllerVerifyEmailResponses]

export type AuthControllerChangePasswordData = {
  body: ChangePasswordInput
  path?: never
  query?: never
  url: '/api/v1/auth/change-password'
}

export type AuthControllerChangePasswordErrors = {
  /**
   * Invalid password format
   */
  400: BaseApiErrorResponse
  /**
   * Invalid current password or authentication required
   */
  401: BaseApiErrorResponse
}

export type AuthControllerChangePasswordError =
  AuthControllerChangePasswordErrors[keyof AuthControllerChangePasswordErrors]

export type AuthControllerChangePasswordResponses = {
  /**
   * Password changed successfully
   */
  200: unknown
}

export type AuthControllerRefreshTokenData = {
  body: RefreshTokenInput
  path?: never
  query?: never
  url: '/api/v1/auth/refresh-token'
}

export type AuthControllerRefreshTokenErrors = {
  401: BaseApiErrorResponse
}

export type AuthControllerRefreshTokenError =
  AuthControllerRefreshTokenErrors[keyof AuthControllerRefreshTokenErrors]

export type AuthControllerRefreshTokenResponses = {
  200: AuthTokenApiResponse
}

export type AuthControllerRefreshTokenResponse =
  AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses]

export type OrganizationControllerGetOrgsData = {
  body?: never
  path?: never
  query: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    name: string
    tagIds: Array<string>
  }
  url: '/api/v1/organizations'
}

export type OrganizationControllerGetOrgsErrors = {
  401: BaseApiErrorResponse
}

export type OrganizationControllerGetOrgsError =
  OrganizationControllerGetOrgsErrors[keyof OrganizationControllerGetOrgsErrors]

export type OrganizationControllerGetOrgsResponses = {
  200: OrganizationArrayApiResponse
}

export type OrganizationControllerGetOrgsResponse =
  OrganizationControllerGetOrgsResponses[keyof OrganizationControllerGetOrgsResponses]

export type OrganizationControllerAddOrgData = {
  body: CreateOrganizationDto
  path?: never
  query?: never
  url: '/api/v1/organizations'
}

export type OrganizationControllerAddOrgErrors = {
  401: BaseApiErrorResponse
}

export type OrganizationControllerAddOrgError =
  OrganizationControllerAddOrgErrors[keyof OrganizationControllerAddOrgErrors]

export type OrganizationControllerAddOrgResponses = {
  200: OrganizationApiResponse
}

export type OrganizationControllerAddOrgResponse =
  OrganizationControllerAddOrgResponses[keyof OrganizationControllerAddOrgResponses]

export type OrganizationControllerDeleteOrganizationData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/organizations/{id}'
}

export type OrganizationControllerDeleteOrganizationErrors = {
  401: BaseApiErrorResponse
}

export type OrganizationControllerDeleteOrganizationError =
  OrganizationControllerDeleteOrganizationErrors[keyof OrganizationControllerDeleteOrganizationErrors]

export type OrganizationControllerDeleteOrganizationResponses = {
  200: OrganizationApiResponse
}

export type OrganizationControllerDeleteOrganizationResponse =
  OrganizationControllerDeleteOrganizationResponses[keyof OrganizationControllerDeleteOrganizationResponses]

export type OrganizationControllerGetOneOrganizationData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/organizations/{id}'
}

export type OrganizationControllerGetOneOrganizationErrors = {
  401: BaseApiErrorResponse
}

export type OrganizationControllerGetOneOrganizationError =
  OrganizationControllerGetOneOrganizationErrors[keyof OrganizationControllerGetOneOrganizationErrors]

export type OrganizationControllerGetOneOrganizationResponses = {
  200: OrganizationApiResponse
}

export type OrganizationControllerGetOneOrganizationResponse =
  OrganizationControllerGetOneOrganizationResponses[keyof OrganizationControllerGetOneOrganizationResponses]

export type OrganizationControllerUpdateOrganizationData = {
  body: UpdateOrganizationDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/organizations/{id}'
}

export type OrganizationControllerUpdateOrganizationErrors = {
  401: BaseApiErrorResponse
}

export type OrganizationControllerUpdateOrganizationError =
  OrganizationControllerUpdateOrganizationErrors[keyof OrganizationControllerUpdateOrganizationErrors]

export type OrganizationControllerUpdateOrganizationResponses = {
  200: OrganizationApiResponse
}

export type OrganizationControllerUpdateOrganizationResponse =
  OrganizationControllerUpdateOrganizationResponses[keyof OrganizationControllerUpdateOrganizationResponses]

export type OrganizationControllerVerifyOrganizationData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/organizations/{id}/verify'
}

export type OrganizationControllerVerifyOrganizationResponses = {
  200: OrganizationApiResponse
}

export type OrganizationControllerVerifyOrganizationResponse =
  OrganizationControllerVerifyOrganizationResponses[keyof OrganizationControllerVerifyOrganizationResponses]

export type TagControllerGetTagsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    tag?: string
    isUserTag?: boolean
    isOrganizationTag?: boolean
    isEventTag?: boolean
    isNewsTag?: boolean
    isOpportunityTag?: boolean
    isProjectTag?: boolean
    isResourceTag?: boolean
  }
  url: '/api/v1/tags'
}

export type TagControllerGetTagsErrors = {
  401: BaseApiErrorResponse
}

export type TagControllerGetTagsError =
  TagControllerGetTagsErrors[keyof TagControllerGetTagsErrors]

export type TagControllerGetTagsResponses = {
  200: TagArrayApiResponse
}

export type TagControllerGetTagsResponse =
  TagControllerGetTagsResponses[keyof TagControllerGetTagsResponses]

export type TagControllerAddTagData = {
  body: AddTagDto
  path?: never
  query?: never
  url: '/api/v1/tags'
}

export type TagControllerAddTagErrors = {
  401: BaseApiErrorResponse
}

export type TagControllerAddTagError =
  TagControllerAddTagErrors[keyof TagControllerAddTagErrors]

export type TagControllerAddTagResponses = {
  200: TagApiResponse
}

export type TagControllerAddTagResponse =
  TagControllerAddTagResponses[keyof TagControllerAddTagResponses]

export type TagControllerGetTagsTypeData = {
  body?: never
  path: {
    type: string
  }
  query?: never
  url: '/api/v1/tags/{type}'
}

export type TagControllerGetTagsTypeErrors = {
  401: BaseApiErrorResponse
}

export type TagControllerGetTagsTypeError =
  TagControllerGetTagsTypeErrors[keyof TagControllerGetTagsTypeErrors]

export type TagControllerGetTagsTypeResponses = {
  200: TagArrayApiResponse
}

export type TagControllerGetTagsTypeResponse =
  TagControllerGetTagsTypeResponses[keyof TagControllerGetTagsTypeResponses]

export type TagControllerDeleteTagData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/tags/{id}'
}

export type TagControllerDeleteTagErrors = {
  401: BaseApiErrorResponse
}

export type TagControllerDeleteTagError =
  TagControllerDeleteTagErrors[keyof TagControllerDeleteTagErrors]

export type TagControllerDeleteTagResponses = {
  200: TagApiResponse
}

export type TagControllerDeleteTagResponse =
  TagControllerDeleteTagResponses[keyof TagControllerDeleteTagResponses]

export type ImagekitControllerGetAuthParamasData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/imagekit'
}

export type ImagekitControllerGetAuthParamasErrors = {
  401: BaseApiErrorResponse
}

export type ImagekitControllerGetAuthParamasError =
  ImagekitControllerGetAuthParamasErrors[keyof ImagekitControllerGetAuthParamasErrors]

export type ImagekitControllerGetAuthParamasResponses = {
  200: ImagekitApiResponse
}

export type ImagekitControllerGetAuthParamasResponse =
  ImagekitControllerGetAuthParamasResponses[keyof ImagekitControllerGetAuthParamasResponses]

export type EventsControllerGetEventsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    title?: string
    tagIds?: Array<string>
    status?:
      | 'DRAFT'
      | 'UNDER_REVIEW'
      | 'PUBLISHED'
      | 'REJECTED'
      | 'IMPROVEMENT_REQUIRED'
  }
  url: '/api/v1/events'
}

export type EventsControllerGetEventsErrors = {
  401: BaseApiErrorResponse
}

export type EventsControllerGetEventsError =
  EventsControllerGetEventsErrors[keyof EventsControllerGetEventsErrors]

export type EventsControllerGetEventsResponses = {
  200: EventArrayApiResponse
}

export type EventsControllerGetEventsResponse =
  EventsControllerGetEventsResponses[keyof EventsControllerGetEventsResponses]

export type EventsControllerAddEventData = {
  body: CreateEventDto
  path?: never
  query?: never
  url: '/api/v1/events'
}

export type EventsControllerAddEventErrors = {
  401: BaseApiErrorResponse
}

export type EventsControllerAddEventError =
  EventsControllerAddEventErrors[keyof EventsControllerAddEventErrors]

export type EventsControllerAddEventResponses = {
  200: EventApiResponse
}

export type EventsControllerAddEventResponse =
  EventsControllerAddEventResponses[keyof EventsControllerAddEventResponses]

export type EventsControllerDeleteEventData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/events/{id}'
}

export type EventsControllerDeleteEventErrors = {
  401: BaseApiErrorResponse
}

export type EventsControllerDeleteEventError =
  EventsControllerDeleteEventErrors[keyof EventsControllerDeleteEventErrors]

export type EventsControllerDeleteEventResponses = {
  200: EventApiResponse
}

export type EventsControllerDeleteEventResponse =
  EventsControllerDeleteEventResponses[keyof EventsControllerDeleteEventResponses]

export type EventsControllerGetOneEventData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/events/{id}'
}

export type EventsControllerGetOneEventErrors = {
  401: BaseApiErrorResponse
}

export type EventsControllerGetOneEventError =
  EventsControllerGetOneEventErrors[keyof EventsControllerGetOneEventErrors]

export type EventsControllerGetOneEventResponses = {
  200: EventApiResponse
}

export type EventsControllerGetOneEventResponse =
  EventsControllerGetOneEventResponses[keyof EventsControllerGetOneEventResponses]

export type EventsControllerUpdateEventData = {
  body: UpdateEventDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/events/{id}'
}

export type EventsControllerUpdateEventErrors = {
  401: BaseApiErrorResponse
}

export type EventsControllerUpdateEventError =
  EventsControllerUpdateEventErrors[keyof EventsControllerUpdateEventErrors]

export type EventsControllerUpdateEventResponses = {
  200: EventApiResponse
}

export type EventsControllerUpdateEventResponse =
  EventsControllerUpdateEventResponses[keyof EventsControllerUpdateEventResponses]

export type EventsControllerModerateEventData = {
  body: ContentModerationDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/events/{id}/moderate'
}

export type EventsControllerModerateEventResponses = {
  200: EventApiResponse
}

export type EventsControllerModerateEventResponse =
  EventsControllerModerateEventResponses[keyof EventsControllerModerateEventResponses]

export type NewsControllerGetNewsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    title?: string
    tagIds?: Array<string>
  }
  url: '/api/v1/news'
}

export type NewsControllerGetNewsErrors = {
  401: BaseApiErrorResponse
}

export type NewsControllerGetNewsError =
  NewsControllerGetNewsErrors[keyof NewsControllerGetNewsErrors]

export type NewsControllerGetNewsResponses = {
  200: ApiResponseOfNewsResponseDtoArray
}

export type NewsControllerGetNewsResponse =
  NewsControllerGetNewsResponses[keyof NewsControllerGetNewsResponses]

export type NewsControllerAddNewsData = {
  body: CreateNewsDto
  path?: never
  query?: never
  url: '/api/v1/news'
}

export type NewsControllerAddNewsErrors = {
  401: BaseApiErrorResponse
}

export type NewsControllerAddNewsError =
  NewsControllerAddNewsErrors[keyof NewsControllerAddNewsErrors]

export type NewsControllerAddNewsResponses = {
  200: ApiResponseOfNewsResponseDto
}

export type NewsControllerAddNewsResponse =
  NewsControllerAddNewsResponses[keyof NewsControllerAddNewsResponses]

export type NewsControllerDeleteNewsData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/news/{id}'
}

export type NewsControllerDeleteNewsErrors = {
  401: BaseApiErrorResponse
}

export type NewsControllerDeleteNewsError =
  NewsControllerDeleteNewsErrors[keyof NewsControllerDeleteNewsErrors]

export type NewsControllerDeleteNewsResponses = {
  200: ApiResponseOfNewsResponseDto
}

export type NewsControllerDeleteNewsResponse =
  NewsControllerDeleteNewsResponses[keyof NewsControllerDeleteNewsResponses]

export type NewsControllerGetOneNewsData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/news/{id}'
}

export type NewsControllerGetOneNewsErrors = {
  401: BaseApiErrorResponse
}

export type NewsControllerGetOneNewsError =
  NewsControllerGetOneNewsErrors[keyof NewsControllerGetOneNewsErrors]

export type NewsControllerGetOneNewsResponses = {
  200: ApiResponseOfNewsResponseDto
}

export type NewsControllerGetOneNewsResponse =
  NewsControllerGetOneNewsResponses[keyof NewsControllerGetOneNewsResponses]

export type NewsControllerUpdateNewsData = {
  body: UpdateNewsDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/news/{id}'
}

export type NewsControllerUpdateNewsErrors = {
  401: BaseApiErrorResponse
}

export type NewsControllerUpdateNewsError =
  NewsControllerUpdateNewsErrors[keyof NewsControllerUpdateNewsErrors]

export type NewsControllerUpdateNewsResponses = {
  200: ApiResponseOfNewsResponseDto
}

export type NewsControllerUpdateNewsResponse =
  NewsControllerUpdateNewsResponses[keyof NewsControllerUpdateNewsResponses]

export type NewsControllerModerateNewsData = {
  body: ContentModerationDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/news/{id}/moderate'
}

export type NewsControllerModerateNewsResponses = {
  200: ApiResponseOfNewsResponseDto
}

export type NewsControllerModerateNewsResponse =
  NewsControllerModerateNewsResponses[keyof NewsControllerModerateNewsResponses]

export type OpportunityControllerGetOpportunitiesData = {
  body?: never
  path?: never
  query: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    title: string
    tagIds?: Array<string>
    status?:
      | 'DRAFT'
      | 'UNDER_REVIEW'
      | 'PUBLISHED'
      | 'REJECTED'
      | 'IMPROVEMENT_REQUIRED'
  }
  url: '/api/v1/opportunities'
}

export type OpportunityControllerGetOpportunitiesErrors = {
  401: BaseApiErrorResponse
}

export type OpportunityControllerGetOpportunitiesError =
  OpportunityControllerGetOpportunitiesErrors[keyof OpportunityControllerGetOpportunitiesErrors]

export type OpportunityControllerGetOpportunitiesResponses = {
  200: OpportunityArrayApiResponse
}

export type OpportunityControllerGetOpportunitiesResponse =
  OpportunityControllerGetOpportunitiesResponses[keyof OpportunityControllerGetOpportunitiesResponses]

export type OpportunityControllerAddOpportutnityData = {
  body: CreateOpportunityDto
  path?: never
  query?: never
  url: '/api/v1/opportunities'
}

export type OpportunityControllerAddOpportutnityErrors = {
  401: BaseApiErrorResponse
}

export type OpportunityControllerAddOpportutnityError =
  OpportunityControllerAddOpportutnityErrors[keyof OpportunityControllerAddOpportutnityErrors]

export type OpportunityControllerAddOpportutnityResponses = {
  200: OpportunityApiResponse
}

export type OpportunityControllerAddOpportutnityResponse =
  OpportunityControllerAddOpportutnityResponses[keyof OpportunityControllerAddOpportutnityResponses]

export type OpportunityControllerDeleteOpportunityData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/opportunities/{id}'
}

export type OpportunityControllerDeleteOpportunityErrors = {
  401: BaseApiErrorResponse
}

export type OpportunityControllerDeleteOpportunityError =
  OpportunityControllerDeleteOpportunityErrors[keyof OpportunityControllerDeleteOpportunityErrors]

export type OpportunityControllerDeleteOpportunityResponses = {
  200: OpportunityApiResponse
}

export type OpportunityControllerDeleteOpportunityResponse =
  OpportunityControllerDeleteOpportunityResponses[keyof OpportunityControllerDeleteOpportunityResponses]

export type OpportunityControllerGetOneOpportunityData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/opportunities/{id}'
}

export type OpportunityControllerGetOneOpportunityErrors = {
  401: BaseApiErrorResponse
}

export type OpportunityControllerGetOneOpportunityError =
  OpportunityControllerGetOneOpportunityErrors[keyof OpportunityControllerGetOneOpportunityErrors]

export type OpportunityControllerGetOneOpportunityResponses = {
  200: OpportunityApiResponse
}

export type OpportunityControllerGetOneOpportunityResponse =
  OpportunityControllerGetOneOpportunityResponses[keyof OpportunityControllerGetOneOpportunityResponses]

export type OpportunityControllerUpdateOpportunityData = {
  body: UpdateOpportunityDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/opportunities/{id}'
}

export type OpportunityControllerUpdateOpportunityErrors = {
  401: BaseApiErrorResponse
}

export type OpportunityControllerUpdateOpportunityError =
  OpportunityControllerUpdateOpportunityErrors[keyof OpportunityControllerUpdateOpportunityErrors]

export type OpportunityControllerUpdateOpportunityResponses = {
  200: OpportunityApiResponse
}

export type OpportunityControllerUpdateOpportunityResponse =
  OpportunityControllerUpdateOpportunityResponses[keyof OpportunityControllerUpdateOpportunityResponses]

export type OpportunityControllerModerateOpportunityData = {
  body: ContentModerationDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/opportunities/{id}/moderate'
}

export type OpportunityControllerModerateOpportunityResponses = {
  200: OpportunityApiResponse
}

export type OpportunityControllerModerateOpportunityResponse =
  OpportunityControllerModerateOpportunityResponses[keyof OpportunityControllerModerateOpportunityResponses]

export type AnalyticsControllerGetAdminAnalyticsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/analytics/admin-dashboard'
}

export type AnalyticsControllerGetAdminAnalyticsResponses = {
  200: ApiResponseOfAdminAnalyticsOutput
}

export type AnalyticsControllerGetAdminAnalyticsResponse =
  AnalyticsControllerGetAdminAnalyticsResponses[keyof AnalyticsControllerGetAdminAnalyticsResponses]

export type AnalyticsControllerGetMonthlyUserStatsData = {
  body?: never
  path?: never
  query: {
    year: string
  }
  url: '/api/v1/analytics/monthly-user-stats'
}

export type AnalyticsControllerGetMonthlyUserStatsResponses = {
  200: ApiResponseOfMonthlyUserStatsResponseDto
}

export type AnalyticsControllerGetMonthlyUserStatsResponse =
  AnalyticsControllerGetMonthlyUserStatsResponses[keyof AnalyticsControllerGetMonthlyUserStatsResponses]

export type BlogControllerFindAllBlogsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    title?: string
    category?: string
    author?: string
    tagIds?: Array<string>
    isDraft?: boolean
    isFeatured?: boolean
    /**
     * Category ID
     */
    categoryId?: string
  }
  url: '/api/v1/blogs'
}

export type BlogControllerFindAllBlogsErrors = {
  401: BaseApiErrorResponse
}

export type BlogControllerFindAllBlogsError =
  BlogControllerFindAllBlogsErrors[keyof BlogControllerFindAllBlogsErrors]

export type BlogControllerFindAllBlogsResponses = {
  200: BlogArrayApiResponse
}

export type BlogControllerFindAllBlogsResponse =
  BlogControllerFindAllBlogsResponses[keyof BlogControllerFindAllBlogsResponses]

export type BlogControllerCreateBlogData = {
  body: CreateBlogDto
  path?: never
  query?: never
  url: '/api/v1/blogs'
}

export type BlogControllerCreateBlogErrors = {
  401: BaseApiErrorResponse
}

export type BlogControllerCreateBlogError =
  BlogControllerCreateBlogErrors[keyof BlogControllerCreateBlogErrors]

export type BlogControllerCreateBlogResponses = {
  201: BlogApiResponse
}

export type BlogControllerCreateBlogResponse =
  BlogControllerCreateBlogResponses[keyof BlogControllerCreateBlogResponses]

export type BlogControllerGetFeaturedBlogsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/blogs/featured'
}

export type BlogControllerGetFeaturedBlogsErrors = {
  401: BaseApiErrorResponse
}

export type BlogControllerGetFeaturedBlogsError =
  BlogControllerGetFeaturedBlogsErrors[keyof BlogControllerGetFeaturedBlogsErrors]

export type BlogControllerGetFeaturedBlogsResponses = {
  200: BlogArrayApiResponse
}

export type BlogControllerGetFeaturedBlogsResponse =
  BlogControllerGetFeaturedBlogsResponses[keyof BlogControllerGetFeaturedBlogsResponses]

export type BlogControllerGetPublishedBlogsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/blogs/published'
}

export type BlogControllerGetPublishedBlogsErrors = {
  401: BaseApiErrorResponse
}

export type BlogControllerGetPublishedBlogsError =
  BlogControllerGetPublishedBlogsErrors[keyof BlogControllerGetPublishedBlogsErrors]

export type BlogControllerGetPublishedBlogsResponses = {
  200: BlogArrayApiResponse
}

export type BlogControllerGetPublishedBlogsResponse =
  BlogControllerGetPublishedBlogsResponses[keyof BlogControllerGetPublishedBlogsResponses]

export type BlogControllerDeleteBlogData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/blogs/{id}'
}

export type BlogControllerDeleteBlogErrors = {
  404: BaseApiErrorResponse
}

export type BlogControllerDeleteBlogError =
  BlogControllerDeleteBlogErrors[keyof BlogControllerDeleteBlogErrors]

export type BlogControllerDeleteBlogResponses = {
  200: BlogApiResponse
}

export type BlogControllerDeleteBlogResponse =
  BlogControllerDeleteBlogResponses[keyof BlogControllerDeleteBlogResponses]

export type BlogControllerFindBlogByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/blogs/{id}'
}

export type BlogControllerFindBlogByIdErrors = {
  404: BaseApiErrorResponse
}

export type BlogControllerFindBlogByIdError =
  BlogControllerFindBlogByIdErrors[keyof BlogControllerFindBlogByIdErrors]

export type BlogControllerFindBlogByIdResponses = {
  200: BlogApiResponse
}

export type BlogControllerFindBlogByIdResponse =
  BlogControllerFindBlogByIdResponses[keyof BlogControllerFindBlogByIdResponses]

export type BlogControllerUpdateBlogData = {
  body: UpdateBlogDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/blogs/{id}'
}

export type BlogControllerUpdateBlogErrors = {
  404: BaseApiErrorResponse
}

export type BlogControllerUpdateBlogError =
  BlogControllerUpdateBlogErrors[keyof BlogControllerUpdateBlogErrors]

export type BlogControllerUpdateBlogResponses = {
  200: BlogApiResponse
}

export type BlogControllerUpdateBlogResponse =
  BlogControllerUpdateBlogResponses[keyof BlogControllerUpdateBlogResponses]

export type BlogControllerBlogActionData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/blogs/{id}/action'
}

export type BlogControllerBlogActionErrors = {
  400: BaseApiErrorResponse
  404: BaseApiErrorResponse
}

export type BlogControllerBlogActionError =
  BlogControllerBlogActionErrors[keyof BlogControllerBlogActionErrors]

export type BlogControllerBlogActionResponses = {
  200: BlogApiResponse
}

export type BlogControllerBlogActionResponse =
  BlogControllerBlogActionResponses[keyof BlogControllerBlogActionResponses]

export type EmailSubscriptionControllerSubscribeData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/email-subscription/subscribe'
}

export type EmailSubscriptionControllerSubscribeResponses = {
  201: unknown
}

export type EmailSubscriptionControllerFindAllData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/email-subscription'
}

export type EmailSubscriptionControllerFindAllResponses = {
  200: unknown
}

export type EmailSubscriptionControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/email-subscription/{id}'
}

export type EmailSubscriptionControllerRemoveResponses = {
  200: unknown
}

export type ProjectControllerFindAllProjectsData = {
  body?: never
  path?: never
  query?: {
    offset?: number
    limit?: number
    title?: string
    status?: 'ONGOING' | 'COMPLETED' | 'UPCOMING'
    isDraft?: boolean
  }
  url: '/api/v1/projects'
}

export type ProjectControllerFindAllProjectsResponses = {
  200: ApiResponseOfProjectResponseDtoArray
}

export type ProjectControllerFindAllProjectsResponse =
  ProjectControllerFindAllProjectsResponses[keyof ProjectControllerFindAllProjectsResponses]

export type ProjectControllerCreateProjectData = {
  body: CreateProjectDto
  path?: never
  query?: never
  url: '/api/v1/projects'
}

export type ProjectControllerCreateProjectErrors = {
  401: BaseApiErrorResponse
}

export type ProjectControllerCreateProjectError =
  ProjectControllerCreateProjectErrors[keyof ProjectControllerCreateProjectErrors]

export type ProjectControllerCreateProjectResponses = {
  201: ApiResponseOfProjectResponseDto
}

export type ProjectControllerCreateProjectResponse =
  ProjectControllerCreateProjectResponses[keyof ProjectControllerCreateProjectResponses]

export type ProjectControllerDeleteProjectData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/projects/{id}'
}

export type ProjectControllerDeleteProjectErrors = {
  404: BaseApiErrorResponse
}

export type ProjectControllerDeleteProjectError =
  ProjectControllerDeleteProjectErrors[keyof ProjectControllerDeleteProjectErrors]

export type ProjectControllerDeleteProjectResponses = {
  200: ApiResponseOfProjectResponseDto
}

export type ProjectControllerDeleteProjectResponse =
  ProjectControllerDeleteProjectResponses[keyof ProjectControllerDeleteProjectResponses]

export type ProjectControllerFindProjectByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/projects/{id}'
}

export type ProjectControllerFindProjectByIdErrors = {
  404: BaseApiErrorResponse
}

export type ProjectControllerFindProjectByIdError =
  ProjectControllerFindProjectByIdErrors[keyof ProjectControllerFindProjectByIdErrors]

export type ProjectControllerFindProjectByIdResponses = {
  200: ApiResponseOfProjectResponseDto
}

export type ProjectControllerFindProjectByIdResponse =
  ProjectControllerFindProjectByIdResponses[keyof ProjectControllerFindProjectByIdResponses]

export type ProjectControllerUpdateProjectData = {
  body: UpdateProjectDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/projects/{id}'
}

export type ProjectControllerUpdateProjectErrors = {
  404: BaseApiErrorResponse
}

export type ProjectControllerUpdateProjectError =
  ProjectControllerUpdateProjectErrors[keyof ProjectControllerUpdateProjectErrors]

export type ProjectControllerUpdateProjectResponses = {
  200: ApiResponseOfProjectResponseDto
}

export type ProjectControllerUpdateProjectResponse =
  ProjectControllerUpdateProjectResponses[keyof ProjectControllerUpdateProjectResponses]

export type ResourceControllerFindAllResourcesData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    title?: string
    type?:
      | 'DOCUMENTARY'
      | 'PODCASTS_AND_TELEVISION'
      | 'COURSES'
      | 'PLANS_AND_POLICIES'
      | 'DATA_RESOURCES'
      | 'PLATFORMS'
      | 'RESEARCH_ARTICLES'
      | 'THESES_AND_DISSERTATIONS'
      | 'CASE_STUDIES'
      | 'REPORTS'
      | 'TOOLKITS_AND_GUIDES'
    level?: 'INTERNATIONAL' | 'REGIONAL' | 'NATIONAL' | 'PROVINCIAL' | 'LOCAL'
    tagIds?: Array<string>
    isDraft?: boolean
  }
  url: '/api/v1/resources'
}

export type ResourceControllerFindAllResourcesResponses = {
  200: ApiResponseOfResourceResponseDtoArray
}

export type ResourceControllerFindAllResourcesResponse =
  ResourceControllerFindAllResourcesResponses[keyof ResourceControllerFindAllResourcesResponses]

export type ResourceControllerCreateResourceData = {
  body: CreateResourceDto
  path?: never
  query?: never
  url: '/api/v1/resources'
}

export type ResourceControllerCreateResourceErrors = {
  401: BaseApiErrorResponse
}

export type ResourceControllerCreateResourceError =
  ResourceControllerCreateResourceErrors[keyof ResourceControllerCreateResourceErrors]

export type ResourceControllerCreateResourceResponses = {
  201: ApiResponseOfResourceResponseDto
}

export type ResourceControllerCreateResourceResponse =
  ResourceControllerCreateResourceResponses[keyof ResourceControllerCreateResourceResponses]

export type ResourceControllerDeleteResourceData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/resources/{id}'
}

export type ResourceControllerDeleteResourceErrors = {
  404: BaseApiErrorResponse
}

export type ResourceControllerDeleteResourceError =
  ResourceControllerDeleteResourceErrors[keyof ResourceControllerDeleteResourceErrors]

export type ResourceControllerDeleteResourceResponses = {
  200: ApiResponseOfResourceResponseDto
}

export type ResourceControllerDeleteResourceResponse =
  ResourceControllerDeleteResourceResponses[keyof ResourceControllerDeleteResourceResponses]

export type ResourceControllerFindResourceByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/resources/{id}'
}

export type ResourceControllerFindResourceByIdErrors = {
  404: BaseApiErrorResponse
}

export type ResourceControllerFindResourceByIdError =
  ResourceControllerFindResourceByIdErrors[keyof ResourceControllerFindResourceByIdErrors]

export type ResourceControllerFindResourceByIdResponses = {
  200: ApiResponseOfResourceResponseDto
}

export type ResourceControllerFindResourceByIdResponse =
  ResourceControllerFindResourceByIdResponses[keyof ResourceControllerFindResourceByIdResponses]

export type ResourceControllerUpdateResourceData = {
  body: UpdateResourceDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/resources/{id}'
}

export type ResourceControllerUpdateResourceErrors = {
  404: BaseApiErrorResponse
}

export type ResourceControllerUpdateResourceError =
  ResourceControllerUpdateResourceErrors[keyof ResourceControllerUpdateResourceErrors]

export type ResourceControllerUpdateResourceResponses = {
  200: ApiResponseOfResourceResponseDto
}

export type ResourceControllerUpdateResourceResponse =
  ResourceControllerUpdateResourceResponses[keyof ResourceControllerUpdateResourceResponses]

export type ResourceControllerModerateResourceData = {
  body: ContentModerationDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/resources/{id}/moderate'
}

export type ResourceControllerModerateResourceResponses = {
  200: ApiResponseOfResourceResponseDto
}

export type ResourceControllerModerateResourceResponse =
  ResourceControllerModerateResourceResponses[keyof ResourceControllerModerateResourceResponses]

export type CategoryControllerFindAllData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional, defaults to 100
     */
    limit?: number
    /**
     * Optional, defaults to 0
     */
    offset?: number
    name?: string
    type?:
      | 'BLOG'
      | 'NEWS'
      | 'EVENTS'
      | 'OPPORTUNITY'
      | 'PROJECT'
      | 'RESOURCE'
      | 'ORGANIZATION'
  }
  url: '/api/v1/categories'
}

export type CategoryControllerFindAllResponses = {
  /**
   * Return all categories.
   */
  200: Array<CategoryResponseDto>
}

export type CategoryControllerFindAllResponse =
  CategoryControllerFindAllResponses[keyof CategoryControllerFindAllResponses]

export type CategoryControllerCreateData = {
  body: CreateCategoryDto
  path?: never
  query?: never
  url: '/api/v1/categories'
}

export type CategoryControllerCreateResponses = {
  /**
   * The category has been successfully created.
   */
  201: CategoryResponseDto
}

export type CategoryControllerCreateResponse =
  CategoryControllerCreateResponses[keyof CategoryControllerCreateResponses]

export type CategoryControllerRemoveData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/categories/{id}'
}

export type CategoryControllerRemoveResponses = {
  /**
   * The category has been successfully deleted.
   */
  200: unknown
}

export type CategoryControllerFindOneData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/categories/{id}'
}

export type CategoryControllerFindOneResponses = {
  /**
   * Return the category.
   */
  200: CategoryResponseDto
}

export type CategoryControllerFindOneResponse =
  CategoryControllerFindOneResponses[keyof CategoryControllerFindOneResponses]

export type CategoryControllerUpdateData = {
  body: UpdateCategoryDto
  path: {
    id: string
  }
  query?: never
  url: '/api/v1/categories/{id}'
}

export type CategoryControllerUpdateResponses = {
  /**
   * The category has been successfully updated.
   */
  200: CategoryResponseDto
}

export type CategoryControllerUpdateResponse =
  CategoryControllerUpdateResponses[keyof CategoryControllerUpdateResponses]

export type AiAssistantControllerGetSessionsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/sessions'
}

export type AiAssistantControllerGetSessionsResponses = {
  /**
   * Returns list of user chat sessions
   */
  200: unknown
}

export type AiAssistantControllerCreateSessionData = {
  body: CreateChatSessionDto
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/sessions'
}

export type AiAssistantControllerCreateSessionResponses = {
  /**
   * Chat session created successfully
   */
  201: unknown
}

export type AiAssistantControllerGetUsageData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/usage'
}

export type AiAssistantControllerGetUsageResponses = {
  /**
   * Returns daily prompt usage (used, limit, remaining)
   */
  200: unknown
}

export type AiAssistantControllerGetMessagesData = {
  body?: never
  path: {
    sessionId: string
  }
  query?: never
  url: '/api/v1/ai-assistant/sessions/{sessionId}/messages'
}

export type AiAssistantControllerGetMessagesResponses = {
  /**
   * Returns list of messages in the session
   */
  200: unknown
}

export type AiAssistantControllerAddMessageData = {
  body: AddMessageDto
  path: {
    sessionId: string
  }
  query?: never
  url: '/api/v1/ai-assistant/sessions/{sessionId}/messages'
}

export type AiAssistantControllerAddMessageResponses = {
  /**
   * Message added successfully
   */
  201: unknown
}

export type AiAssistantControllerDeleteSessionData = {
  body?: never
  path: {
    sessionId: string
  }
  query?: never
  url: '/api/v1/ai-assistant/sessions/{sessionId}'
}

export type AiAssistantControllerDeleteSessionResponses = {
  /**
   * Session deleted successfully
   */
  200: unknown
}

export type AiAssistantControllerUpdateSessionData = {
  body: UpdateSessionTitleDto
  path: {
    sessionId: string
  }
  query?: never
  url: '/api/v1/ai-assistant/sessions/{sessionId}'
}

export type AiAssistantControllerUpdateSessionResponses = {
  /**
   * Session title updated successfully
   */
  200: unknown
}

export type AiAssistantControllerDeleteAllDocumentsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/documents'
}

export type AiAssistantControllerDeleteAllDocumentsResponses = {
  /**
   * All documents deleted successfully
   */
  200: unknown
}

export type AiAssistantControllerCreateDocumentData = {
  body: CreateDocumentDto
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/documents'
}

export type AiAssistantControllerCreateDocumentResponses = {
  /**
   * Document created successfully
   */
  201: unknown
}

export type AiAssistantControllerGetDocumentBySourceData = {
  body?: never
  path: {
    sourceUrl: string
  }
  query?: never
  url: '/api/v1/ai-assistant/documents/by-source/{sourceUrl}'
}

export type AiAssistantControllerGetDocumentBySourceResponses = {
  /**
   * Returns document if found
   */
  200: unknown
}

export type AiAssistantControllerCreateChunkData = {
  body: CreateChunkDto
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/chunks'
}

export type AiAssistantControllerCreateChunkResponses = {
  /**
   * Chunk created successfully
   */
  201: unknown
}

export type AiAssistantControllerGetChunksByIdsData = {
  body: GetChunksDto
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/chunks/batch'
}

export type AiAssistantControllerGetChunksByIdsResponses = {
  /**
   * Returns chunks with document metadata
   */
  200: unknown
}

export type AiAssistantControllerChatData = {
  body: ChatRequestDto
  path?: never
  query?: never
  url: '/api/v1/ai-assistant/chat'
}

export type AiAssistantControllerChatResponses = {
  /**
   * Returns AI response with sources and session ID
   */
  201: unknown
}

export type DatabaseControllerExportData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/database/export'
}

export type DatabaseControllerExportErrors = {
  /**
   * Internal server error
   */
  500: unknown
}

export type DatabaseControllerExportResponses = {
  /**
   * ZIP file containing the database dump
   */
  200: unknown
}

export type ClientOptions = {
  baseUrl: string
}
