name: Deploy NCH CMS Frontend

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10.11.1

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: pnpm

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: ./dist

      - name: Deploy to Web Server Directory
        run: |
          echo "Build artifact downloaded. Deploying to runner..."
          # Deploy to the specified path
          cp -rv ./dist/* /home/azureuser/cms--frontend/dist
